version: '3.7'

services:
    backend:
        image: 123160087/express:main
        container_name: backend-express
        ports:
            - 3000:3000
        networks:
            - deploy
        depends_on:
            - postgres
        environment: 
            - PORT=3000
            - REDIS_HOST=redis
            - DB_HOST=postgres
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=POS
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 200M
                reservations:
                    cpus: '1'
                    memory: 200M    

postgres:
        image: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=POS
        ports:
            - 5432:5432
        networks: 
            - deploy
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    redis:
        image: redis
        container_name: redis
        environment: 
            - REDIS_PORT=6379
            - REDIS_PASSWORD=redis123
        ports: 
            - 6379:6379
        networks:
            - deploy
        volumes:
            - ./redis-data:/var/lib/redis

networks:
    deploy:
        driver: bridge
    
volumes:
    postgres-data:
    redis-data:
